#!/usr/bin/env ruby
# frozen_string_literal: true

require "csv"
require "fileutils"

root = File.expand_path("..", __dir__)
manifest_path = File.join(root, "manifests", "remaining_core_papers_for_fulltext_v0.csv")
out_dir = File.join(root, "manifests")
assignment_path = File.join(out_dir, "branch_assignment_v0.csv")
summary_path = File.join(out_dir, "branch_assignment_summary_v0.md")
workpack_dir = File.join(root, "workpacks")

rows = CSV.read(manifest_path, headers: true)

BRANCH_PRIORITY = [
  ["review_benchmark_meta_comparison", %w[review]],
  ["frustrated_spin_j1j2", %w[frustrated_spin]],
  ["sign_structure_symmetry", %w[symmetry]],
  ["optimization_sr_minsr_linear_scalable", %w[optimization]],
  ["architecture_cnn_gcnn_rnn_transformer_foundation", %w[architecture foundation_model]],
  ["fermionic_chemistry_hubbard", %w[fermionic chemistry continuous_space nuclear]],
  ["dynamics_time_evolution", %w[dynamics open_system]],
  ["tomography_experimental_reconstruction", %w[tomography]],
  ["general_nqs_expressivity", %w[general_nqs theory_expressivity topological benchmark]]
].freeze

def normalize_tags(value)
  value.to_s.split(";").map(&:strip).reject(&:empty?)
end

def primary_branch(tags)
  matched = BRANCH_PRIORITY.find { |_branch, keys| (tags & keys).any? }
  matched ? matched.first : "other_nqs"
end

def secondary_branches(tags, primary)
  BRANCH_PRIORITY.each_with_object([]) do |(branch, keys), branches|
    next if branch == primary
    branches << branch if (tags & keys).any?
  end
end

FileUtils.mkdir_p(out_dir)
FileUtils.mkdir_p(workpack_dir)

CSV.open(assignment_path, "w") do |csv|
  csv << [
    "universe_id",
    "title",
    "authors",
    "year",
    "visible_date",
    "url",
    "original_branch_tags",
    "primary_branch",
    "secondary_branches",
    "assigned_batch",
    "quality_tier",
    "relevance_score",
    "why_include",
    "extraction_priority",
    "paper_local_first"
  ]

  rows.each do |row|
    tags = normalize_tags(row["branch_tags"])
    primary = primary_branch(tags)
    secondary = secondary_branches(tags, primary)
    relevance = row["relevance_score"].to_s
    priority =
      if relevance == "manual" || relevance.to_i >= 7
        "high"
      elsif relevance.to_i >= 6
        "medium"
      else
        "standard"
      end

    csv << [
      row["universe_id"],
      row["title"],
      row["authors"],
      row["year"],
      row["visible_date"],
      row["url"],
      row["branch_tags"],
      primary,
      secondary.join(";"),
      row["assigned_batch"],
      row["quality_tier"],
      row["relevance_score"],
      row["why_include"],
      priority,
      "true"
    ]
  end
end

assigned = CSV.read(assignment_path, headers: true)
branch_counts = assigned.group_by { |row| row["primary_branch"] }.transform_values(&:size).sort_by { |k, v| [-v, k] }
priority_counts = assigned.group_by { |row| row["extraction_priority"] }.transform_values(&:size).sort_by { |k, _v| k }
year_counts = assigned.group_by { |row| row["year"] }.transform_values(&:size).sort_by { |k, _v| k.to_s }

assigned.group_by { |row| row["primary_branch"] }.each do |branch, branch_rows|
  path = File.join(workpack_dir, "#{branch}.csv")
  CSV.open(path, "w") do |csv|
    csv << assigned.headers
    branch_rows.sort_by { |row| [row["year"].to_s, row["universe_id"].to_s] }.each { |row| csv << row }
  end
end

File.open(File.join(workpack_dir, "README.md"), "w") do |f|
  f.puts "# NQS 100plus Branch Workpacks V0"
  f.puts
  f.puts "Generated by:"
  f.puts
  f.puts "- `scripts/build_branch_assignments.rb`"
  f.puts
  f.puts "Source manifest:"
  f.puts
  f.puts "- `manifests/branch_assignment_v0.csv`"
  f.puts
  f.puts "## How To Use"
  f.puts
  f.puts "Each CSV in this folder is a branch-aware workpack. Workers should perform paper-local extraction first:"
  f.puts
  f.puts "1. locate source / full text;"
  f.puts "2. create section map;"
  f.puts "3. extract author-stated evidence nodes;"
  f.puts "4. extract paper-internal evidence edges;"
  f.puts "5. record possible cross-paper candidates;"
  f.puts "6. avoid broad strict cross-paper development edges unless direct full-text evidence is found."
  f.puts
  f.puts "Primary branch is an organizing label only. It is not evidence."
  f.puts
  f.puts "## Workpacks"
  f.puts
  branch_counts.each do |branch, count|
    f.puts "- `#{branch}.csv`: #{count} papers"
  end
end

File.open(summary_path, "w") do |f|
  f.puts "# NQS 100plus Branch Assignment Summary V0"
  f.puts
  f.puts "Generated from:"
  f.puts
  f.puts "- `manifests/remaining_core_papers_for_fulltext_v0.csv`"
  f.puts
  f.puts "Output:"
  f.puts
  f.puts "- `manifests/branch_assignment_v0.csv`"
  f.puts
  f.puts "## Purpose"
  f.puts
  f.puts "The original 206-paper manifest is round-robin batched. This file creates a branch-aware view so workers can perform paper-local extraction while the controller later performs branch-local cross-paper linking."
  f.puts
  f.puts "The primary branch is only an organizing label. It is not an evidence node and must not be used as proof of a scientific relation."
  f.puts
  f.puts "## Primary Branch Counts"
  f.puts
  f.puts "| primary_branch | papers |"
  f.puts "|---|---:|"
  branch_counts.each { |branch, count| f.puts "| `#{branch}` | #{count} |" }
  f.puts
  f.puts "## Extraction Priority Counts"
  f.puts
  f.puts "| extraction_priority | papers |"
  f.puts "|---|---:|"
  priority_counts.each { |priority, count| f.puts "| `#{priority}` | #{count} |" }
  f.puts
  f.puts "## Year Counts"
  f.puts
  f.puts "| year | papers |"
  f.puts "|---|---:|"
  year_counts.each { |year, count| f.puts "| #{year} | #{count} |" }
  f.puts
  f.puts "## Branch Priority Rule"
  f.puts
  f.puts "If a paper has multiple tags, assign the first matching primary branch in this order:"
  f.puts
  BRANCH_PRIORITY.each_with_index do |(branch, keys), index|
    f.puts "#{index + 1}. `#{branch}`: #{keys.map { |key| "`#{key}`" }.join(', ')}"
  end
  f.puts
  f.puts "This ordering intentionally prioritizes review/meta papers, then the J1-J2/frustrated-spin seed line, then symmetry/sign, optimization, architecture, fermionic/chemistry, dynamics, tomography, and finally general expressivity."
end

puts "Wrote #{assignment_path}"
puts "Wrote #{summary_path}"
puts "Wrote workpacks to #{workpack_dir}"
